import{a as L,S,i}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="51936128-dd4753b80012efeea137add36",v="https://pixabay.com/api/",b=15;async function E(r,t){const s={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:b};return(await L.get(v,{params:s})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function q(r){const t=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:a,comments:g,downloads:p})=>`
 <li>
 <a href="${n}">
 <img src="${s}" alt="${e}" />
 </a>
 <div class="info">
 <p>Likes: ${o}</p>
 <p>Views: ${a}</p>
 <p>Comments: ${g}</p>
 <p>Downloads: ${p}</p>
 </div>
 </li>
 `).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}function M(){d.innerHTML=""}function $(){f.classList.remove("hidden")}function B(){f.classList.add("hidden")}function x(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}const O=document.querySelector(".form"),A=document.querySelector(".load-more");let c=1,h="",l=0;const H=40;O.addEventListener("submit",_);A.addEventListener("click",D);async function y(r){r===1&&M(),$(),u();try{const t=await E(h,r),{hits:s,totalHits:n}=t;if(r===1){if(l=n,s.length===0){i.error({title:"No results",message:"Sorry, there are no images matching your search query."});return}i.success({title:"Success",message:`We found ${l} images.`})}q(s);const e=Math.ceil(l/H);c<e?x():(u(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(t){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(t)}finally{B()}}async function _(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){i.error({title:"Error",message:"Please enter a search query!"});return}h=t,c=1,await y(c),r.target.elements["search-text"].value=t}async function D(){c+=1,await y(c),I()}function I(){const r=document.querySelector(".gallery li");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
