import{a as L,S,i}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="51936128-dd4753b80012efeea137add36",v="https://pixabay.com/api/",b=40;async function E(t,r){const s={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:b};return(await L.get(v,{params:s})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function q(t){const r=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:a,comments:g,downloads:p})=>`
 <li>
 <a href="${n}">
 <img src="${s}" alt="${e}" />
 </a>
 <div class="info">
 <p>Likes: ${o}</p>
 <p>Views: ${a}</p>
 <p>Comments: ${g}</p>
 <p>Downloads: ${p}</p>
 </div>
 </li>
 `).join("");d.insertAdjacentHTML("beforeend",r),P.refresh()}function M(){d.innerHTML=""}function $(){f.classList.remove("hidden")}function B(){f.classList.add("hidden")}function x(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}const O=document.querySelector(".form"),A=document.querySelector(".load-more");let c=1,h="",l=0;const H=40;O.addEventListener("submit",T);A.addEventListener("click",_);async function y(t){t===1&&M(),$(),u();try{const r=await E(h,t),{hits:s,totalHits:n}=r;if(console.log("Fetched page:",t,"Results:",s.length,"Total:",n),t===1){if(l=n,s.length===0){i.error({title:"No results",message:"Sorry, there are no images matching your search query."});return}i.success({title:"Success",message:`We found ${l} images.`})}q(s);const e=Math.ceil(l/H);c<e&&s.length>0?x():t!==1&&(u(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(r){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(r)}finally{B()}}async function T(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){i.error({title:"Error",message:"Please enter a search query!"});return}h=r,c=1,await y(c),t.target.elements["search-text"].value=r}async function _(){c+=1,await y(c),D()}function D(){const t=document.querySelector(".gallery li");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
