import{a as L,S,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="51729015-e356512e01098e6cfb5d1c735",b="https://pixabay.com/api/",q=15;async function v(r,t){const n={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:q};return(await L.get(b,{params:n})).data}const u=document.querySelector(".gallery"),d=document.querySelector(".loader"),f=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function P(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:g,downloads:p})=>`
 <li>
 <a href="${s}">
 <img src="${n}" alt="${e}" />
 </a>
 <div class="info">
 <p>Likes: ${o}</p>
 <p>Views: ${i}</p>
 <p>Comments: ${g}</p>
 <p>Downloads: ${p}</p>
 </div>
 </li>
 `).join("");u.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){u.innerHTML=""}function B(){d.classList.remove("hidden")}function M(){d.classList.add("hidden")}function A(){f.classList.remove("hidden")}function O(){f.classList.add("hidden")}const m=document.querySelector(".form"),x=document.querySelector(".load-more");let l=1,y="",c=0;m.addEventListener("submit",H);x.addEventListener("click",I);async function h(r){B(),O();try{const t=await v(y,r),{hits:n,totalHits:s}=t;if(r===1){if(c=s,$(),n.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query."});return}a.success({title:"Success",message:`We found ${c} images.`})}P(n);const e=document.querySelectorAll(".gallery li").length;e<c?A():e>=c&&r>1&&a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}catch(t){a.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(t)}finally{M()}}async function H(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){a.error({title:"Error",message:"Please enter a search query!"});return}y=t,l=1,await h(l),m.reset()}async function I(){l+=1,await h(l),_()}function _(){const r=document.querySelector(".gallery li");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
